on:
  push:
    branches: [ "main" ]

jobs:
  test-382:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Execute unit tests
      run: dotnet test MSTestClassInitializeInconclusive/MSTestClassInitializeInconclusive.csproj

  test-373:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Execute unit tests
      run: dotnet test MSTestClassInitializeInconclusive373/MSTestClassInitializeInconclusive373.csproj